version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - /Users/asnawisaharuddin/projects/epsa-docker/mysql/conf:/etc/mysql/conf.d
      - /Users/asnawisaharuddin/projects/epsa-docker/mysql/storage:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_USER}"
      MYSQL_DATABASE: "${MYSQL_DB}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PWD}"

  site:
    depends_on:
      - db
    image: registry.gitlab.com/asnawisaharuddin/epsa-docker:latest
    volumes:
      - /Users/asnawisaharuddin/projects/epsa:/var/www/html
    entrypoint:
      - bash
      - -c
      - |
        set -e

        cd /var/www/html/lms/lms405 && bower install --allow-root
        cd /var/www/html/lms/lms405 && composer install --verbose --prefer-dist --no-progress --no-interaction --no-suggest --optimize-autoloader
        echo 'initialization done, starting apache'
        /usr/sbin/apache2ctl -D FOREGROUND
    ports:
      - "80:80"
    restart: always
    environment:
      DB_HOST: db
      DB_USER: "${EPSA_DB_USER}"
      DB_PASSWORD: "${EPSA_DB_PWD}"
